# Generated by Django 5.0.1 on 2024-01-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moliya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imtihon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('sana', models.DateField()),
                ('talaba_soni', models.BigIntegerField()),
                ('sayt', models.CharField(max_length=30)),
                ('yillik', models.CharField(max_length=30)),
            ],
        ),
    ]
