# Generated by Django 5.0.1 on 2024-01-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moliya', '0002_imtihon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('yosh', models.BigIntegerField()),
                ('jins', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='notebook',
            name='nom',
            field=models.CharField(choices=[('HP', 'HP'), ('Acer', 'Acer'), ('Asus', 'Asus'), ('Lenovo', 'Lenovo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='rasm',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='yangi',
            field=models.BooleanField(default=False),
        ),
    ]
