# Generated by Django 5.0.1 on 2024-01-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moliya', '0003_talaba_alter_notebook_nom_alter_notebook_rasm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('login', models.CharField(max_length=30, unique=True)),
                ('parol', models.BigIntegerField()),
                ('email', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=30)),
                ('talaba', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=30)),
                ('rasm', models.FileField(upload_to='')),
            ],
        ),
    ]
