# Generated by Django 5.0.1 on 2024-01-13 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moliya', '0004_foydalanuvchi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('daraja', models.CharField(choices=[("Boshlang'ich", "Boshlang'ich"), ("O'rta", "O'rta"), ('Yuqori', 'Yuqori')], max_length=30)),
                ('narx', models.BigIntegerField()),
                ('chegirma', models.CharField(default=0, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
                ('yosh', models.BigIntegerField()),
                ('jins', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baho', models.CharField(max_length=20)),
                ('matn', models.CharField(max_length=20)),
                ('sana', models.DateField()),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moliya.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moliya.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Xarid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('holat', models.CharField(choices=[('Tugatildi', 'Tugatildi'), ('Davom etyabdi', 'Davom etyapti'), ('Boshlanmagan', 'Boshlanmagan')], max_length=20)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moliya.kurs')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moliya.profil')),
            ],
        ),
    ]
