# Generated by Django 5.0.1 on 2024-01-20 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moliya', '0005_kurs_profil_izoh_xarid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanlangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moliya.kurs')),
                ('profil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moliya.profil')),
            ],
        ),
    ]
